site_name: Mandrakodi Wiki
site_description: Guida e documentazione per Mandrakodi
site_author: MandraKodi

theme:
  name: material
  language: it
  palette:
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Passa al tema chiaro
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Passa al tema scuro
  features:
    - navigation.tabs
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Installazione: installazione/install.md
  - Guide: guide/tutorials.md
  - FAQ: faq/faq.md
  - Assistenza: ask_help.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css
