name: Sync With Test

on:
  push:
    branches:
      - main

jobs:
  sincronizzazione:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Esegui Sync su repository Sync
        run: |
          git remote add destination "https://x-access-token:${{ secrets.TEST_SYNC }}@github.com/campipaolo/Sync.git"
          git push --force destination main
