name: Sync With Test

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "campipaolo/Mandrakodi-Wiki"
          source_branch: "main"
          destination_repo: "https://campipaolo:${{ secrets.REPO_TOKEN }}@github.com/campipaolo/Sync.git"
          destination_branch: "main"
