name: Sync With Test

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura Git e Push su Sync
        run: |
          git config --global user.name "campipaolo"
          git config --global user.email "campipaolo@users.noreply.github.com"
          git remote add target "https://campipaolo:${{ secrets.Test_Sync }}@github.com/campipaolo/Sync.git"
          git push --force target main
